# Generated by Django 4.2.6 on 2023-10-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Objet IoT',
                'verbose_name_plural': 'Objets IoT',
            },
        ),
        migrations.CreateModel(
            name='IoTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotapp.iotobject')),
            ],
            options={
                'verbose_name': 'Donnée IoT',
                'verbose_name_plural': 'Données IoT',
            },
        ),
    ]
