# Generated by Django 4.2.6 on 2023-10-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('iotapp', '0003_alter_iotobject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotobject',
            name='auth_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
